/****************************************************************************
*
* krt - Ken's Raytracer - Coursework Edition. (C) Copyright 1993-2022.
*
* I've put a lot of time and effort into this code. For the last decade
* it's been used to introduce hundreds of students at multiple universities
* to raytracing. It forms the basis of your coursework but you are free
* to continue using/developing forever more. However, I ask that you don't
* share the code or your derivitive versions publicly. In order to continue
* to be used for coursework and in particular assessment it's important that
* versions containing solutions are not searchable on the web or easy to
* download.
*
* If you want to show off your programming ability, instead of releasing
* the code, consider generating an incredible image and explaining how you
* produced it.
*/

// simple Camera is has a 90 degree field of view along the z axis.
#ifndef _SIMPLE_CAMERA_H_
#define _SIMPLE_CAMERA_H_

#include "../Core/camera.h"

class SimpleCamera: public Camera{
public:
	float width;
	float height;
  float fov;

  SimpleCamera();

  SimpleCamera(float p_f);

  void get_ray_pixel(int p_x, int p_y, Ray &p_ray);

  // given an Environment, call env.raytrace() on each of the rays generated by get_ray_pixel
  // and store the result in the framebuffer
  void render(Environment& env, FrameBuffer& fb);
};

#endif
